dataset:
  name: CIFARSelfSupScale
  scale:
    min_scale: 0.5
    max_scale: 2.0
  cifar_version: 10
model:
  name: L2NetNaiveModel
  kw: {}
  loss: [0.7, PeakyLoss, 0.3, CSELoss]
  # loss: [loss_weight, loss_name, ...] 
  # ex) [0.5, CseLoss, 0.4, PeakyLoss]
optimizer:
  name: Adam
  kw: 
    lr: 0.001
metadata:
  exp_name: baseline
  gpu: [1]
  bsz: 64
  epoch: 20
  train_val_ratio: 0.80
  validate_every: 1
  wandb_log: true
validation:
  correct_threshold: 3